// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhTdjhzA6k2BJ60sjlf3aCCIaYx6FcaUI',
    appId: '1:345455774454:web:24933421ab566a02b33ad7',
    messagingSenderId: '345455774454',
    projectId: 'memorymateauth1',
    authDomain: 'memorymateauth1.firebaseapp.com',
    storageBucket: 'memorymateauth1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhfk2whQ17Y9Y5uANr16--5PR0HIcLClQ',
    appId: '1:345455774454:android:74ba253cefcb01eab33ad7',
    messagingSenderId: '345455774454',
    projectId: 'memorymateauth1',
    storageBucket: 'memorymateauth1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4pZB8MMcnQNnghPl4UvTMLZk-VSQ7jSw',
    appId: '1:345455774454:ios:d5ce12ccecf757bcb33ad7',
    messagingSenderId: '345455774454',
    projectId: 'memorymateauth1',
    storageBucket: 'memorymateauth1.appspot.com',
    iosClientId: '345455774454-n7ksml37c34fkjvqsv4m4j27ln3i15s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4pZB8MMcnQNnghPl4UvTMLZk-VSQ7jSw',
    appId: '1:345455774454:ios:268ae10a423043f8b33ad7',
    messagingSenderId: '345455774454',
    projectId: 'memorymateauth1',
    storageBucket: 'memorymateauth1.appspot.com',
    iosClientId: '345455774454-2f7m1qs8tk5vtj9f40vvg34jv1t87svd.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld.RunnerTests',
  );
}
